max_workers_ratio: 1.0
add:
  max_scene_length: 50
analyse:
  features: &analyse_features
    - name: "clip"
      pretrained_model: "openai/clip-vit-base-patch16"
      batch_size: 16
    - name: "ocr"
      batch_size: 8
    - name: "yolo"
      pretrained_model: "yolov8l-oiv7.pt"
      batch_size: 16
  num_workers: 1
  pin_memory: true

milvus:
  fields:
    - field_name: "frame_id"
      datatype: "VARCHAR"
      max_length: 32
      is_primary: true
    - field_name: "clip"
      datatype: "FLOAT_VECTOR"
      dim: 512
    - field_name: "ocr"
      datatype: "JSON"
    - field_name: "yolo"
      datatype: "JSON"
  indices:
    - field_name: "clip"
      metric_type: "COSINE"
      index_type: "IVF_FLAT"
      index_name: "clip_index"
      params:
        nlist: 128

webui:
  features: *analyse_features
  database: "milvus"
  search:
    timeout: null
    request_size: 10
    backends:
      - host: http://127.0.0.1:5100
  video:
    timeout: null
    request_size: 10
    backends:
      - host: http://127.0.0.1:5100
