import { getAvailableModels } from "../services/search.js";
export const nlist = 128;
export const ef_default = 32;
export const nprobeOption = [512, 256, 128, 32, 8];
export const limitOptions = [10, 15, 20, 50];
export const temporal_k_default = 500;
export const ocr_weight_default = 1;
export const ocr_threshold_default = 40;
export const object_weight_default = 1;
export const max_interval_default = 1000;
